version: '2'
services:
  storage:
   image: busybox
   volumes:
     - /var/lib/mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes_from:
      - storage
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  fake_sqs:
    image: h3poteto/fake_sqs
    ports:
      - "4568:4568"
    hostname: fake_sqs.com
    command: /usr/local/bundle/bin/fake_sqs --bind fake_sqs.com
  rails:
    image: h3poteto/rails
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3001:3000"
    links:
      - fake_sqs:fake_sqs.com
      - mysql:mysql
    command: /bin/bash
  shoryuken:
    image: h3poteto/rails
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
    volumes:
      - .:/usr/src/app
    links:
      - fake_sqs:fake_sqs.com
      - mysql:mysql
    command: bundle exec shoryuken -R -C config/shoryuken.yml
