aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "access key id" %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "secret access key" %>
  region: <%= ENV["AWS_REGION"] || "region" %>
  sqs_endpoint: <%= ENV["AWS_SQS_ENDPOINT"] || "http://localhost:4568" %>
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
verbose: false
concurrency: 10
delay: 25
pidfile: ./tmp/pids/shoryuken.pid
logfile: ./log/shoryuken.log
queues:
  - <%= Settings.sqs.queue.patient %>
