user_name: 'asumi_syndrome'
analytics: false
site:
  http: 'http://192.168.99.100:3002/'
  fqdn: 'http://192.168.99.100:3002/'
  host: '192.168.99.100:3002'
  blog: 'http://yaplog.jp/asumibiyori/index1_0.rdf'
twitter:
  user_name: <%# settings.local overrides %>
  ## アプリ登録時に取得したCONSUMER_KEY/CONSUMER_SECRET
  consumer_key: <%# settings.local overrides %>
  consumer_secret: <%# settings.local overrides %>
  ## irbで取得したAccess Token/Access Secret
  oauth_token: <%# settings.local overrides %>
  oauth_token_secret: <%# settings.local overrides %>