user_name: 'asumi_syndrome'
analytics: true
site:
  http: 'http://www.asumi.ch/'
  fqdn: 'http://www.asumi.ch/'
  host: 'asumi.ch'
  blog: 'http://yaplog.jp/asumibiyori/index1_0.rdf'
twitter:
  user_name: <%# settings.local overrides %>
  ## アプリ登録時に取得したCONSUMER_KEY/CONSUMER_SECRET
  consumer_key: <%# settings.local overrides %>
  consumer_secret: <%# settings.local overrides %>
  ## irbで取得したAccess Token/Access Secret
  oauth_token: <%# settings.local overrides %>
  oauth_token_secret: <%# settings.local overrides %>
redis: