require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NiconicomoviesController do

  # This should return the minimal set of attributes required to create a valid
  # Niconicomovie. As you add validations to Niconicomovie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NiconicomoviesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all niconicomovies as @niconicomovies" do
      niconicomovie = Niconicomovie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:niconicomovies).should eq([niconicomovie])
    end
  end

  describe "GET show" do
    it "assigns the requested niconicomovie as @niconicomovie" do
      niconicomovie = Niconicomovie.create! valid_attributes
      get :show, {:id => niconicomovie.to_param}, valid_session
      assigns(:niconicomovie).should eq(niconicomovie)
    end
  end

  describe "GET new" do
    it "assigns a new niconicomovie as @niconicomovie" do
      get :new, {}, valid_session
      assigns(:niconicomovie).should be_a_new(Niconicomovie)
    end
  end

  describe "GET edit" do
    it "assigns the requested niconicomovie as @niconicomovie" do
      niconicomovie = Niconicomovie.create! valid_attributes
      get :edit, {:id => niconicomovie.to_param}, valid_session
      assigns(:niconicomovie).should eq(niconicomovie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Niconicomovie" do
        expect {
          post :create, {:niconicomovie => valid_attributes}, valid_session
        }.to change(Niconicomovie, :count).by(1)
      end

      it "assigns a newly created niconicomovie as @niconicomovie" do
        post :create, {:niconicomovie => valid_attributes}, valid_session
        assigns(:niconicomovie).should be_a(Niconicomovie)
        assigns(:niconicomovie).should be_persisted
      end

      it "redirects to the created niconicomovie" do
        post :create, {:niconicomovie => valid_attributes}, valid_session
        response.should redirect_to(Niconicomovie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved niconicomovie as @niconicomovie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Niconicomovie.any_instance.stub(:save).and_return(false)
        post :create, {:niconicomovie => {  }}, valid_session
        assigns(:niconicomovie).should be_a_new(Niconicomovie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Niconicomovie.any_instance.stub(:save).and_return(false)
        post :create, {:niconicomovie => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested niconicomovie" do
        niconicomovie = Niconicomovie.create! valid_attributes
        # Assuming there are no other niconicomovies in the database, this
        # specifies that the Niconicomovie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Niconicomovie.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => niconicomovie.to_param, :niconicomovie => { "these" => "params" }}, valid_session
      end

      it "assigns the requested niconicomovie as @niconicomovie" do
        niconicomovie = Niconicomovie.create! valid_attributes
        put :update, {:id => niconicomovie.to_param, :niconicomovie => valid_attributes}, valid_session
        assigns(:niconicomovie).should eq(niconicomovie)
      end

      it "redirects to the niconicomovie" do
        niconicomovie = Niconicomovie.create! valid_attributes
        put :update, {:id => niconicomovie.to_param, :niconicomovie => valid_attributes}, valid_session
        response.should redirect_to(niconicomovie)
      end
    end

    describe "with invalid params" do
      it "assigns the niconicomovie as @niconicomovie" do
        niconicomovie = Niconicomovie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Niconicomovie.any_instance.stub(:save).and_return(false)
        put :update, {:id => niconicomovie.to_param, :niconicomovie => {  }}, valid_session
        assigns(:niconicomovie).should eq(niconicomovie)
      end

      it "re-renders the 'edit' template" do
        niconicomovie = Niconicomovie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Niconicomovie.any_instance.stub(:save).and_return(false)
        put :update, {:id => niconicomovie.to_param, :niconicomovie => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested niconicomovie" do
      niconicomovie = Niconicomovie.create! valid_attributes
      expect {
        delete :destroy, {:id => niconicomovie.to_param}, valid_session
      }.to change(Niconicomovie, :count).by(-1)
    end

    it "redirects to the niconicomovies list" do
      niconicomovie = Niconicomovie.create! valid_attributes
      delete :destroy, {:id => niconicomovie.to_param}, valid_session
      response.should redirect_to(niconicomovies_url)
    end
  end

end
