require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SerifsController do

  # This should return the minimal set of attributes required to create a valid
  # Serif. As you add validations to Serif, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SerifsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all serifs as @serifs" do
      serif = Serif.create! valid_attributes
      get :index, {}, valid_session
      assigns(:serifs).should eq([serif])
    end
  end

  describe "GET show" do
    it "assigns the requested serif as @serif" do
      serif = Serif.create! valid_attributes
      get :show, {:id => serif.to_param}, valid_session
      assigns(:serif).should eq(serif)
    end
  end

  describe "GET new" do
    it "assigns a new serif as @serif" do
      get :new, {}, valid_session
      assigns(:serif).should be_a_new(Serif)
    end
  end

  describe "GET edit" do
    it "assigns the requested serif as @serif" do
      serif = Serif.create! valid_attributes
      get :edit, {:id => serif.to_param}, valid_session
      assigns(:serif).should eq(serif)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Serif" do
        expect {
          post :create, {:serif => valid_attributes}, valid_session
        }.to change(Serif, :count).by(1)
      end

      it "assigns a newly created serif as @serif" do
        post :create, {:serif => valid_attributes}, valid_session
        assigns(:serif).should be_a(Serif)
        assigns(:serif).should be_persisted
      end

      it "redirects to the created serif" do
        post :create, {:serif => valid_attributes}, valid_session
        response.should redirect_to(Serif.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serif as @serif" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serif.any_instance.stub(:save).and_return(false)
        post :create, {:serif => {  }}, valid_session
        assigns(:serif).should be_a_new(Serif)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serif.any_instance.stub(:save).and_return(false)
        post :create, {:serif => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serif" do
        serif = Serif.create! valid_attributes
        # Assuming there are no other serifs in the database, this
        # specifies that the Serif created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Serif.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => serif.to_param, :serif => { "these" => "params" }}, valid_session
      end

      it "assigns the requested serif as @serif" do
        serif = Serif.create! valid_attributes
        put :update, {:id => serif.to_param, :serif => valid_attributes}, valid_session
        assigns(:serif).should eq(serif)
      end

      it "redirects to the serif" do
        serif = Serif.create! valid_attributes
        put :update, {:id => serif.to_param, :serif => valid_attributes}, valid_session
        response.should redirect_to(serif)
      end
    end

    describe "with invalid params" do
      it "assigns the serif as @serif" do
        serif = Serif.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serif.any_instance.stub(:save).and_return(false)
        put :update, {:id => serif.to_param, :serif => {  }}, valid_session
        assigns(:serif).should eq(serif)
      end

      it "re-renders the 'edit' template" do
        serif = Serif.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serif.any_instance.stub(:save).and_return(false)
        put :update, {:id => serif.to_param, :serif => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serif" do
      serif = Serif.create! valid_attributes
      expect {
        delete :destroy, {:id => serif.to_param}, valid_session
      }.to change(Serif, :count).by(-1)
    end

    it "redirects to the serifs list" do
      serif = Serif.create! valid_attributes
      delete :destroy, {:id => serif.to_param}, valid_session
      response.should redirect_to(serifs_url)
    end
  end

end
