require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YoutubemoviesController do

  # This should return the minimal set of attributes required to create a valid
  # Youtubemovie. As you add validations to Youtubemovie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YoutubemoviesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all youtubemovies as @youtubemovies" do
      youtubemovie = Youtubemovie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:youtubemovies).should eq([youtubemovie])
    end
  end

  describe "GET show" do
    it "assigns the requested youtubemovie as @youtubemovie" do
      youtubemovie = Youtubemovie.create! valid_attributes
      get :show, {:id => youtubemovie.to_param}, valid_session
      assigns(:youtubemovie).should eq(youtubemovie)
    end
  end

  describe "GET new" do
    it "assigns a new youtubemovie as @youtubemovie" do
      get :new, {}, valid_session
      assigns(:youtubemovie).should be_a_new(Youtubemovie)
    end
  end

  describe "GET edit" do
    it "assigns the requested youtubemovie as @youtubemovie" do
      youtubemovie = Youtubemovie.create! valid_attributes
      get :edit, {:id => youtubemovie.to_param}, valid_session
      assigns(:youtubemovie).should eq(youtubemovie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Youtubemovie" do
        expect {
          post :create, {:youtubemovie => valid_attributes}, valid_session
        }.to change(Youtubemovie, :count).by(1)
      end

      it "assigns a newly created youtubemovie as @youtubemovie" do
        post :create, {:youtubemovie => valid_attributes}, valid_session
        assigns(:youtubemovie).should be_a(Youtubemovie)
        assigns(:youtubemovie).should be_persisted
      end

      it "redirects to the created youtubemovie" do
        post :create, {:youtubemovie => valid_attributes}, valid_session
        response.should redirect_to(Youtubemovie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved youtubemovie as @youtubemovie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Youtubemovie.any_instance.stub(:save).and_return(false)
        post :create, {:youtubemovie => {  }}, valid_session
        assigns(:youtubemovie).should be_a_new(Youtubemovie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Youtubemovie.any_instance.stub(:save).and_return(false)
        post :create, {:youtubemovie => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested youtubemovie" do
        youtubemovie = Youtubemovie.create! valid_attributes
        # Assuming there are no other youtubemovies in the database, this
        # specifies that the Youtubemovie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Youtubemovie.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => youtubemovie.to_param, :youtubemovie => { "these" => "params" }}, valid_session
      end

      it "assigns the requested youtubemovie as @youtubemovie" do
        youtubemovie = Youtubemovie.create! valid_attributes
        put :update, {:id => youtubemovie.to_param, :youtubemovie => valid_attributes}, valid_session
        assigns(:youtubemovie).should eq(youtubemovie)
      end

      it "redirects to the youtubemovie" do
        youtubemovie = Youtubemovie.create! valid_attributes
        put :update, {:id => youtubemovie.to_param, :youtubemovie => valid_attributes}, valid_session
        response.should redirect_to(youtubemovie)
      end
    end

    describe "with invalid params" do
      it "assigns the youtubemovie as @youtubemovie" do
        youtubemovie = Youtubemovie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Youtubemovie.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtubemovie.to_param, :youtubemovie => {  }}, valid_session
        assigns(:youtubemovie).should eq(youtubemovie)
      end

      it "re-renders the 'edit' template" do
        youtubemovie = Youtubemovie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Youtubemovie.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtubemovie.to_param, :youtubemovie => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested youtubemovie" do
      youtubemovie = Youtubemovie.create! valid_attributes
      expect {
        delete :destroy, {:id => youtubemovie.to_param}, valid_session
      }.to change(Youtubemovie, :count).by(-1)
    end

    it "redirects to the youtubemovies list" do
      youtubemovie = Youtubemovie.create! valid_attributes
      delete :destroy, {:id => youtubemovie.to_param}, valid_session
      response.should redirect_to(youtubemovies_url)
    end
  end

end
